version: '3'
services:
  robjinman-com-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/robjinman.com
  robjinman-com-prisma:
    build:
      context: .
      dockerfile: ./deployment/prisma/Dockerfile
      args:
        PRISMA_CONFIG: |
          managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
          port: 4466
          databases:
            default:
              migrations: true
              connector: postgres
              host: robjinman-com-db
              port: 5432
              user: prisma
              password: prisma
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            migrations: true
            connector: postgres
            host: robjinman-com-db
            port: 5432
            user: prisma
            password: prisma
    ports:
      - 4466:4466
    depends_on:
      - robjinman-com-db
  robjinman-com-api:
    build:
      context: .
      dockerfile: ./deployment/api/Dockerfile
    environment:
      PRISMA_ENDPOINT: http://robjinman-com-prisma:4466
      PRISMA_MANAGEMENT_API_SECRET: ${PRISMA_MANAGEMENT_API_SECRET}
      PRISMA_SECRET: ${PRISMA_SECRET}
      APP_SECRET: ${APP_SECRET}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - 4000:4000
    depends_on:
      - robjinman-com-prisma
volumes:
  postgres:
